name: Biome (lint + format)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Install Node (via Volta)
        run: volta install node@22.17.1

      - name: Install pnpm (via Volta)
        run: volta install pnpm@10.13.1

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: pnpm check
